# Generated by Django 5.2.5 on 2025-09-01 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=15)),
                ('cat_desc', models.TextField()),
                ('cat_foto', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=40)),
                ('cli_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('cli_titulo_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('cli_direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('cli_ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('cli_region', models.CharField(blank=True, max_length=15, null=True)),
                ('cli_codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_pais', models.CharField(blank=True, max_length=15, null=True)),
                ('cli_telefono', models.CharField(blank=True, max_length=24, null=True)),
                ('cli_mail', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=20)),
                ('emp_apellido', models.CharField(max_length=10)),
                ('emp_titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_mail', models.EmailField(blank=True, max_length=25, null=True)),
                ('emp_fechanac', models.DateField(blank=True, null=True)),
                ('emp_fecha_contrato', models.DateField(blank=True, null=True)),
                ('emp_direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('emp_celular', models.CharField(blank=True, max_length=24, null=True)),
                ('emp_foto', models.BinaryField(blank=True, null=True)),
                ('emp_notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('prv_empresa', models.CharField(max_length=40)),
                ('prv_giro', models.CharField(max_length=20)),
                ('prv_contacto', models.CharField(max_length=30)),
                ('prv_direccion', models.CharField(max_length=60)),
                ('prv_pco_postal', models.CharField(max_length=10)),
                ('prv_telefono', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('ord_fecha', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='Pfront.cliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pfront.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=40)),
                ('pro_descripcion', models.CharField(max_length=30)),
                ('pro_precio', models.DecimalField(decimal_places=4, max_digits=19)),
                ('pro_stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pfront.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, to='Pfront.orden')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Pfront.producto')),
            ],
        ),
    ]
